/**
 * Do not edit directly
 * Generated by Style Dictionary
 */

export const tokens = {
  palette: {
    yellow: {
      '90': '#826400',
      '100': '#594500',
    },
    blue: {
      '20': '#bbdefb',
      '30': '#63a4ff',
      '40': '#1976d2',
    },
    red: {
      '20': '#ffcdd2',
      '30': '#e57373',
      '40': '#d32f2f',
    },
  },
  typography: {
    fontWeight: '800',
    fontSize: '16px',
    fontFamily: 'Arial Black',
  },
  button: {
    contained: {
      primary: {
        bg: {
          hover: '#594500',
        },
      },
    },
  },
  ts: {
    sem: {
      colour: {
        primary: {
          main: '#1976d2',
        },
      },
    },
  },
} as const;

export type Tokens = typeof tokens;
